server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# 巡检结果存储数据库
database:
  default:
    link:   "sqlite::@file(manifest/db/user.db)"
    debug:  true


# 管理员初始化管理员账号和密码，只有第一次有效
admin:
  username: admin
  password: admin

# 登录 token 存活时间，单位分钟
tokenAliveTime: 120

# Coding 个人令牌
coding-openapi:
  token: 2ad26b32e126ade248ba7222cdc6ee00ed47de43
  url: http://codingcorp.coding.dev-010.devops-cloud.club